### ISSUE TITLE
Consider using a sprite for monster images

### ISSUE THREAD

**Issue by dropyghost** [swarfarm/swarfarm#102]
Something like this will improve the loading time of user profiles. The problem with multiple images is each download add the network latency.

You can use a css sprite generator like this one

https://spritegen.website-performance.org/

To have images like this:

![download](https://user-images.githubusercontent.com/10077853/53974243-977a5080-40d8-11e9-8041-4d05686b613f.png)

Are the monster images available on the github repository? I will like to do some testing with more pictures together.  I could take some more from the site but will take time.

**Comment by Xzandro** [comment]
In times of http/2, are sprites really that needed? For me personally, it's stuff from the past (if you use http/2, which SWARFARM does). I think there could be a small performance boost, but not sure if it's worth the effort anymore.

**Comment by dropyghost** [comment]
That is why I want do some testing. Do you know where are the images?

Also maybe has to consider not everyone has high speed internet. I have 6mbps and I can see the images loading one by one.

**Comment by Xzandro** [comment]
[Here](https://github.com/PeteAndersen/swarfarm/tree/master/herders/static/herders/images) are the images.

**Comment by PeteAndersen** [comment]
I considered and rejected it a long time ago due to maintenance headaches. It's not as simple as slapping the images into a sprite and putting some CSS on a tag. It would require significant automation in the data import aspect and I won't consider a do-it-by-hand approach.

Additionally any solution here in this code may not be worth the time as the frontend is being redeveloped in VueJS and will be handling all of the static images.
