### ISSUE TITLE
Displays white page when I want to visit and old profile

### ISSUE THREAD

**Issue by DimGael** [swarfarm/swarfarm#115]
I often click on an old swarfarm profile on Reddit and swarfarm sometimes displays an empty white page.

It would be cool to display an error here because I don't know if my internet is broken, if the profile doesn't exist, or if it's a private profile.

# How to reproduce the white page

- Here is a link which is displaying white : https://swarfarm.com/profile/Chaldramus/ 

# Links after my few tests
- Here is a link which is displaying a "private profile" message : https://swarfarm.com/profile/Test/
- Here is a link which is displaying a 404 error : https://swarfarm.com/profile/jenaimarre%C3%A7amarchepas/

**Comment by PeteAndersen** [comment]
Thanks, I've fixed the code which was returning a 404 response without any content when a profile was not found. Note that your last link does not contain a valid username and fails because it does not match any URL routes. Usernames may only contain plain alphanumeric, _, @, +, . and - characters.

In regards to old links, they may or may not work depending on how old. On Jan 28th the site recovered from a total data loss and old profiles are permanently gone, unless they were recreated by the user. You can review the news in the oldest posts on the home page.
