### ISSUE TITLE
Make Original Rune Quality Clearer on Monster Instance Page

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#123]
Goal: make it more obvious which runes need to be replaced, which the current UI—and the game—hide way too well. Brought to you by discovering that I had originally blue runes on way too many high-level monsters and getting better runes on them made them work better. Since upgrading runes turns them into more desirable colors, that makes them *appear* to be better runes than they actually are. Sigh.

The simplest UI fix would be, in the Runes section, to the left of the slot number, put a several pixel line colored like the original rune color. Since hovering over the slot number loads the popup, and that popup shows the original rune quality near where the line is on the underlying page, I think that makes the context clear even if it isn't initially.

I think this might help prevent some people from powering up some awful-to-meh runes.

Thoughts? Better ideas?

**Comment by PeteAndersen** [comment]
I like the idea. Here's how it looks implemented as you described:

![image](https://user-images.githubusercontent.com/11867035/73239725-d4688f00-4151-11ea-8bf8-7578e28984e9.png)

I think it looks pretty good, but I'll leave this issue open for a little bit to see if there are any other comments on how to present. 

(p.s. no judging the rune selections, this was just random stuff from my inventory 😄)

**Comment by deirdresm** [comment]
Perfect! Would you like me to submit the pull request or do you have it already?

(No judging at all. After I filed this, I found that one of the monsters I use every day had an orignally normal rune and another had an originally magic rune. They were just powered up so they appeared to be legend runes to my relatively inexperienced eyes.)

**Comment by claytondaley** [comment]
This came into my email with a title so I knew what I was looking for.  It still took me a second to find the color.  I suspect it's because tables generally include this kind of information to the right of the identifier column (e,g. the slot number).

Food for thought:

 - Color the right border too (but it's also outside the usual "data" range)
 - Make it the background color (too?) using a high transparency so it looks "light"

**Comment by claytondaley** [comment]
At the same time I use an optimizer to select runes for my monsters.  If that's the ideal build, I don't really care whether it's a blue rune with great rolls or a legendary rune with trash rolls.  I mostly care about rune quality (after it's +12) when deciding what to ReApp (so it's useful to me but mostly when considering inventory runes).

**Comment by PeteAndersen** [comment]
@deirdresm I already have the code done, don't worry about a PR

As @claytondaley points out the original quality isn't the main piece of information about a rune, but it is useful to know so I want to keep it subtle but also immediately visible. Instead of a table border, which is not always used when displaying a rune, I changed it to this which I can instead use throughout the site (including monster popovers in the profile box view):

![image](https://user-images.githubusercontent.com/11867035/73327945-b6139980-420c-11ea-98e4-a348848e3a2e.png)

**Comment by deirdresm** [comment]
Thank you! I was away all day yesterday, so I wanted to address part of Clayton's comments.

Yes, SWOP is wonderful…for what it does do, but the focus is too micro. Example. I just moved from a starter guild to our sister main guild and was told we need more nat 4* siege defenses and did I have any please? So I'm looking through all my nat 4* and trying to strengthen any of them I can. That's not a SWOP-level tune, it's an overall improvement.

Also, there's the situation I was in for a month where I literally was unable to find SWOP builds for my Bernard. I know, I know, farm harder (and I did), but I realized 6* him would also have met the design goals.

I like the changes, so thank you Pete.

**Comment by claytondaley** [comment]
Because I use a tool called [RuneManager](https://github.com/Skibisky/RuneManager), I have a SWOP-level build for every 5*+ (current evolution not natural stars) as well as a couple 4* that I expect to use soonish.  

The tool has a much steeper learning curve than SWOP (and some non-fatal bugs), but it's also more flexible:

 - I recall it being very hard to try several builds (Swift + Focus, Swift + Energy, Swift + Guard) in SWOP.  RM lets me select arbitrarily many sets and it will optimize them all at once.
 - Because it's written in C# (vs java), RM is MUCH faster and it doesn't run out of memory with large permutation counts.
 - You configure a "scoring" system for each build.  There less flexibility because it just picks the highest build (vs. giving you a list), but it means it can (re)run every build while you're AFK.
 - In my experience, the damage calculation is better out-of-the-box and the tool has a DPS (damage per second) option that accounts for speed.

Nothing against SWOP... which is amazing for new players.  Just clarifying that I actually do have SWOP builds for everything and it's not because I spend 40h a week on the game.

**Comment by deirdresm** [comment]
Oh how cool! I'm not a C# person and in fact just uninstalled Microsoft Studio (which I could reinstall), but I like that idea a lot. I may however want to re-implement it in Swift just because I'm that sort of person. :P

I'd also wanted to do some experimenting with alternative rune scoring for non-attack monsters or attack monsters who scale on stats other than attack/cr/cd.
