### ISSUE TITLE
Artifacts: Group by att/hp/def within element/attribute

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#154]
Most of the time, it seems that people want attack artifacts, just looking at what people have equipped, YouTube, etc. So the current sorting strictly by element/attribute and power up doesn't really make it obvious what's available if you're looking for how many attack fire artifacts you may have.

**Comment by QuatZo** [comment]
Yeah, having it internally grouped by main stat would be a lot better, because right now sorting is quite counter-intuitive.
Did you have something like this in mind?
![image](https://user-images.githubusercontent.com/48104274/98252755-9323cc00-1f7a-11eb-82cb-f1307f7e94c3.png)

**Comment by deirdresm** [comment]
Yes, exactly. Though since most people seem to want ATK most, putting that first makes the most sense.

**Comment by QuatZo** [comment]
It's not possible to order them by main stat on database level and have ATK first, because it occurs to be 2nd choice (in Swarfarm and C2U) out of 3.
Counter on the right side should resolve issue #155.
![art](https://user-images.githubusercontent.com/48104274/98291612-aef39600-1fab-11eb-97f0-6243b3866b47.png)
