### ISSUE TITLE
Search: Searching on the base type does not find 2A variants

### ISSUE THREAD

**Issue by deirdresm** [swarfarm/swarfarm#157]
If you search on Inugami in the monster name field in the monster filter, it'll find both awakened and unawakened inugami, but not second awakened inugami.

Same is true of werewolf and griffon, though I didn't check other 2A monsters; I assume it's the same.

Monster name search should also find 2A monsters that are of that type. (Also, for those servers that have the imperfect monster variant, e.g., Japan, I don't know if search filter breaks there.)

<img width="832" alt="Screen Shot 2020-10-24 at 19 29 37" src="https://user-images.githubusercontent.com/10251429/97097611-81affb00-162f-11eb-9271-27cb84a44f79.png">

**Comment by deirdresm** [comment]
<img width="705" alt="Screen Shot 2020-10-24 at 19 29 52" src="https://user-images.githubusercontent.com/10251429/97097641-1fa3c580-1630-11eb-8349-c163e9bc43c6.png">

None of my 6*/5* 2A Inugami are shown (Belladeon, Kro, Raoq, Icaru). Given that I was trying to plan skillups, that made planning for today's secret dungeon needs harder. Like: I'll need to use actual paper. :P

**Comment by QuatZo** [comment]
From what I've seen, search filter should be able to find Imperfect (Japan) monsters if you use base monster name. It probably won't work if you type i.e. "Jojo" since Imperfect versions are not connected to base (**should they be?**).

I've added filter for 2A -> Base monster name, it works for monsters with and without 2A versions.
![2a](https://user-images.githubusercontent.com/48104274/98239197-e04a7280-1f67-11eb-96c0-331d08f799b1.png)
![normal](https://user-images.githubusercontent.com/48104274/98239193-dfb1dc00-1f67-11eb-8449-3f2d66f0b9be.png)

**Edit**
I'm not sure how commits and pull requests from forked repo works, if something wrong let me know.
