### ISSUE TITLE
Permalink to filter settings

### ISSUE THREAD

**Issue by PeteAndersen** [swarfarm/swarfarm#16]
https://swarfarm.com/feedback/376/

* Bestiary
* Monsters
* Runes

**Comment by QuatZo** [comment]
Kind of late, but working on it. Should be done in few days for every possible filter. ~The only problem is with `bootstrap-slider`, it's kind of strange. I need to create new with values from Query, then delete old. It results in some layout problems~. Nevermind, I tried to use `bootstrapSlider` instead of `slider`.
![image](https://user-images.githubusercontent.com/48104274/99128476-2f993e80-260b-11eb-8c6d-2fe6150650d8.png)

Example query with filters shown above
`https://<swarfarm>/profile/<some_profile>/?monster__name=inugami&stars=2%2C3&monster__natural_stars=1%2C5&level=1%2C40&tags__pk=1&tags__pk=2&priority=1&priority=2&priority=3&monster__archetype=attack&monster__archetype=hp&monster__archetype=support&monster__element=pure&monster__element=fire&monster__element=wind&monster__awaken_level=0&monster__awaken_level=1&fodder=None&in_storage=True&monster__fusion_food=False&buff_debuff_effects=22&buff_debuff_effects=23&other_effects=75&monster__skills__scaling_stats__pk=25&monster__skills__passive=True&monster__skills__aoe=False&monster__skills__cooltime=4%2C9&monster__skills__hits=1%2C5&monster__leader_skill__attribute=5&monster__leader_skill__area=1&monster__leader_skill__area=5`
