### ISSUE TITLE
Artifacts not adding their main stat to total stats

### ISSUE THREAD

**Issue by jocagos** [swarfarm/swarfarm#171]
When looking at a monster's stats, the total stats do NOT reflect the stats added by artifacts. I have two current examples:
![WhatsApp Image 2020-11-09 at 01 11 55](https://user-images.githubusercontent.com/22819690/98510434-b70c3980-2228-11eb-912c-313e8100f31c.jpeg)
![image](https://user-images.githubusercontent.com/22819690/98510498-dc00ac80-2228-11eb-90a4-34a20a2c7d27.png)
![WhatsApp Image 2020-11-09 at 01 11 56](https://user-images.githubusercontent.com/22819690/98510525-e458e780-2228-11eb-930a-bbaeceabe9ea.jpeg)
![image](https://user-images.githubusercontent.com/22819690/98510566-f63a8a80-2228-11eb-8a0e-3289edfd8357.png)

**Comment by QuatZo** [comment]
There are 2 possible ways to do this.
1. Add Artifact column (and also artifact_hp, artifact_attack & artifact_defense in MonsterInstance model) and calculate these values independently from runes:
![image](https://user-images.githubusercontent.com/48104274/98556344-3d656180-22a3-11eb-9887-4f3fa7388d1c.png)
2. Add Artifact main stat values directly to formula, under Rune (notice ATK stat being higher than in previous screenshot)
![image](https://user-images.githubusercontent.com/48104274/98556472-5ff77a80-22a3-11eb-970e-a31743c95a95.png)

@PeteAndersen I would need you to make a decision which option you prefer.

**Comment by QuatZo** [comment]
It also refers to [feedback 144](https://swarfarm.com/feedback/144/)

**Comment by PeteAndersen** [comment]
I think I'd prefer option 2 to lump in with the runes. The artifact column would be pretty sparse with a max of 2 rows with any data.

**Comment by QuatZo** [comment]
I've decided to merge both options, taking UI from 2nd option (as Porksmash said) and model structure from 1st (because artifacts are not runes).
Artifact mainstat value is stored under `artifact_<mainstat>` in every monster instance. It's being added to `rune_<stat>` for every situation like in screenshots provided above. Whenever `total_<stat>` for HP, Attack & Defense is used, artifacts are also included into calculations.

As you can see on the screenshot below, it represents the same monster as in my previous screenshots. Akhamamir has equipped only one artifact, which gives him +100 Attack and it's calculated (in UI) together with runes.
![image](https://user-images.githubusercontent.com/48104274/98684049-06a44f80-2366-11eb-8fb8-b4a6413eb563.png)
In database, artifact values are separated from Rune values
![image](https://user-images.githubusercontent.com/48104274/98684205-2e93b300-2366-11eb-9611-5a8cba517d84.png)
