### ISSUE TITLE
Monsters in Monster Sealed Shrine not visible in Swarfarm

### ISSUE THREAD

**Issue by QuatZo** [swarfarm/swarfarm#178]
After yesterday's update (v6.1.0) and introduction of new bulding (Monster Sealed Shrine), if monsters are stored in this building, these are no longer visible in Swarfarm.

I did some digging in JSON Profile file we get from SWEX and - sadly - these monsters are no longer in `unit_list` key. I thought it works similar to Material Storage Building, when we can store units like Rainbowmons. New building has ID `83` (*building_master_id*), but sadly there's no other reference. 

Also, there's new command `getUnitStorageList`. I think its response contains what we are looking for, since it has `unit_master_id` same as monster `unit_master_id` from existing Monster objects, together with `quantity` and `class`.
[Example request](https://pastebin.com/CWq8wGYB)
[Example response](https://pastebin.com/G2C7nRFJ)

I don't think there's anything we can do, unless merging `HubUserLogin` command with `getUnitStorageList` at the built-in Profile plugin level, so people using webpage can import whole monster collection, not only the ones in inventory and normal storage.

**Comment by Xzandro** [comment]
I added automatic merging to SWEX, which might help with this.

**Comment by deirdresm** [comment]
I thought I'd add a note to this based on my own Sealed Shrine.

It has the rule that you can't store an awakened monster unless it was summoned awakened. Fine, as they're a different unit_master_id, but here are my unawakened Fire Salamanders, and that one that was summoned awakened as a Krakdon:

[…]
    {
      "unit_master_id": 11102,
      "class": 3,
      "quantity": 5
    },
    {
      "unit_master_id": 11112,
      "class": 4,
      "quantity": 1
    },
[…]

So just be aware that they won't all be unawakened.

I actually like the differentiation as I have a bad habit of hanging onto things I've summoned awakened, assuming that I've awakened them for some reason and have since forgotten. Sometimes, they're just more useful fodder. Now I can know that if they're in that building, they're usable.

**Comment by QuatZo** [comment]
@Xzandro do you need to release new SWEX version with updated built-in plugin or is it somehow automatically fetched? I don't know Express :/

**Comment by Xzandro** [comment]
I need to release a new version, which I will within 2-5 days.

**Comment by QuatZo** [comment]
Added Monster Shrine Storage to already existing Material Storage, sorted by awakening level (unawakened first), then by name. Also, these monsters are now considered while checking skill ups. Is there any other place it would be great to check Monster Shrine storage?

GIF below, let me know if something needs to be changed.
![monster_shrine](https://user-images.githubusercontent.com/48104274/100680239-6bedce00-3371-11eb-9768-a4bd125ad572.gif)

**Comment by Xzandro** [comment]
[SWEX 0.0.36](https://github.com/Xzandro/sw-exporter/releases/latest) is now available.

**Comment by QuatZo** [comment]
Should be done, Fusion system also adjusted
![fusion](https://user-images.githubusercontent.com/48104274/101280937-660e4780-37cc-11eb-8194-ac38a6b849a9.gif)
