### ISSUE TITLE
cant save runes to mons

### ISSUE THREAD

**Issue by buttsbuttsbutts67** [swarfarm/swarfarm#42]
so i'm trying to add runes to my mons but they wont save and i dont see an option to save... when i create a rune under the rune menu it also doesnt save and shows nothing in the runes menu... am i just missing something?
![screen shot 2017-03-30 at 8 00 28 pm](https://cloud.githubusercontent.com/assets/26805557/24532140/a9cb5608-1583-11e7-9fb0-ab878f4bc9c3.png)

**Comment by PeteAndersen** [comment]
When creating (after clicking Create New in your screenshot there) the save button is in the bottom left side. You might have to scroll down. I notice that you don't actually have any runes at all, which is why the results in your screenshot is blank. That screen only shows runes you already have unequipped.

![image](https://cloud.githubusercontent.com/assets/11867035/24532840/5b9be85e-1578-11e7-8f89-ac5ceb8fe1be.png)

I'd also suggest using SW-Exporter, a tool I've worked on with another developer, which can extract all of your game information. You can then import it into swarfarm from here: https://swarfarm.com/data/import/swjson/

**Comment by buttsbuttsbutts67** [comment]
even when i'm on that screen and create+save it doesnt show up after. it doesn't show up in the rune menu and it doesnt show up equipped to the mon... i've tried a few times... is sw-exporter mac/iphone compatible?

**Comment by PeteAndersen** [comment]
I can't recreate your issues here - I just did it on the live site. If you want to keep trying, press F12 and bring up the javascript console and let me know if there are any errors.

Yes it is compatible with Mac. I forgot to include a link: https://github.com/Xzandro/sw-exporter/releases
Step by step instructions are in the program once you get it running but I can also answer any questions that aren't there.
