### ISSUE TITLE
Feature request: Rune last seen equipped tracking

### ISSUE THREAD

**Issue by cloudeigh** [swarfarm/swarfarm#63]
Hi Porksmash,

One thing I've been thinking would be nice for the last few months was a column to show when the a rune was last seen equipped (if ever). It would be great so I could at a glance see what runes haven't been used in a long time, and consider junking them. 

I'm happy to have a go at making a pull request with this change, if you wouldn't mind pointing me in the right direction for columns on the runes page. (I have 0 familiarity with this project code so not sure where to start!)

Primax from Discord / RapnerSA(Global)

**Comment by PeteAndersen** [comment]
The rune model would be in [herders/models.py](https://github.com/porksmash/swarfarm/blob/master/herders/models.py#L1466) with the actual fields starting at L1988. It's a ridiculously long file and the model is giant due to the number of constants I needed for runes, sorry. 

For the implementation you're thinking, what datatype would this new column be? Datetime? Foreign key to the monster?
