### ISSUE TITLE
Profile import client side

### ISSUE THREAD

**Issue by futrtrubl** [swarfarm/swarfarm#79]
Would it be possible to do the processing of json imports etc client side reducing the server load and queues?

**Comment by PeteAndersen** [comment]
Have you frequently noticed extended queue times? I would imagine that the longest part of the process is actually uploading the json file itself. You have not actually entered the queue until the progress page loads. In that case, it would be reasonable to parse the json file client side and only send the required portions. Checking on my own export it reduces the file size from 1248kb to 878kb which is a pretty good reduction, and should translate directly to 30% reduced overall time (neglecting the time it takes to parse a 1.2MB JSON file in client browser). 

I don't believe moving the ENTIRE process client side would greatly speed up much, mostly because updating each monster, rune, and other stuff would require one POST request per item, meaning 1000+ requests for a normal end-game account full of runes and monsters. Overall I think that is more total data transferred than uploading the json file.

**Comment by futrtrubl** [comment]
I wasn't sure if processing cycles affect your hosting costs.
Regarding transfer size I'm presuming that it's sent uncompressed and human readable text. Would compression or conversion to machine readable binary help things? Or is that too much work for too little gain?

**Comment by PeteAndersen** [comment]
Actually server resources are entirely donated right now, so there is no cost and currently no major bottlenecks. From my point of view the best return on time would be trimming the file prior to upload. I think some better UI indication of upload progress would psychologically help as well.

**Comment by futrtrubl** [comment]
Fair enough. I shall close this then.
